services:
  # ─────────────────────────────────────────────
  # PostgreSQL
  # ─────────────────────────────────────────────
  postgres:
    image: postgres:16-alpine
    container_name: sports-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: sports
      # DATABASE_URL: "postgresql://postgres:docker@localhost:5432/dsports?schema=public"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d -sports" ]
      interval: 10s
      timeout: 5s
      retries: 5
  # ─────────────────────────────────────────────
  # Backend — Fastify + Prisma
  # ─────────────────────────────────────────────
  # backend:
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile
  #     target: production
  #   container_name: sports-backend
  #   restart: unless-stopped
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   environment:
  #     NODE_ENV: production
  #     PORT: 4949
  #     DATABASE_URL: postgresql://${POSTGRES_USER:-sports}:${POSTGRES_PASSWORD:-sports}@postgres:5432/${POSTGRES_DB:-sports}
  #     JWT_SECRET_KEY: y8f6b28edf1c44088be0abc46910996798f361bb3567b839a03aeefd77fa44c164ddf8a67759930d6411818d00cd831e5ff4d34323af174f188f7050199bfe7a5

  #   ports:
  #     - "4949:4949"
  #   healthcheck:
  #     test: ["CMD-SHELL", "wget -qO- http://localhost:4949/health || exit 1"]
  #     interval: 15s
  #     timeout: 5s
  #     retries: 5
  #     start_period: 30s

  # ─────────────────────────────────────────────
  # Frontend — React (nginx)
  # ─────────────────────────────────────────────
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #     target: production
  #   container_name: sports-frontend
  #   restart: unless-stopped
  #   depends_on:
  #     backend:
  #       condition: service_healthy
  #   ports:
  #     - "80:80"

volumes:
  postgres_data:
